#!/bin/bash
clear
apt-get install update
apt-get install upgrade
apt update
apt upgrade -y
apt-get install python -y
apt install requirements.txt

echo -e "\e[1m\e[31mWARNING donot Subscribe :\e[32m Termux Tricks & Tut"
echo
echo -e "\e[1m\e[31m ENTER :\e[32exit"
echo
